name: Release Dispatch

on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.0.0
        with:
          token: ${{ secrets.PA_TOKEN }}
          repository: TheJaeger/test-compiler
          event-type: test-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
